// Disease Classes Constants
// Story 3.2: On-Device Disease Detection Model
// AC2: Model recognizes 50+ diseases, pests, and nutrient deficiencies
// AC5: Model covers major Pakistani crops (wheat, rice, cotton, sugarcane, corn)
// AC6: Results include disease name in English and local language

/**
 * Disease Categories
 */
export const DISEASE_CATEGORIES = {
  FUNGAL: 'fungal',
  BACTERIAL: 'bacterial',
  VIRAL: 'viral',
  PEST: 'pest',
  NUTRIENT_DEFICIENCY: 'nutrient_deficiency',
  OTHER: 'other',
};

/**
 * Severity Levels
 */
export const SEVERITY_LEVELS = {
  MILD: 'mild',
  MODERATE: 'moderate',
  SEVERE: 'severe',
  CRITICAL: 'critical',
};

/**
 * Disease Database - 50+ Diseases for Pakistani Crops
 * 
 * Each entry maps a model class ID to disease information
 * Covers: Wheat, Rice, Cotton, Sugarcane, Corn + Nutrient Deficiencies
 */
export const DISEASE_CLASSES = [
  // ============ HEALTHY CLASS (Class 0) ============
  {
    id: 'disease-000',
    classId: 0,
    nameEn: 'Healthy',
    nameUr: 'صحت مند',
    namePa: 'صحت مند',
    nameSd: 'صحتمند',
    scientificName: null,
    category: DISEASE_CATEGORIES.OTHER,
    severity: SEVERITY_LEVELS.MILD,
    affectedCrops: ['wheat', 'rice', 'cotton', 'sugarcane', 'corn'],
    descriptionEn: 'Healthy plant with no signs of disease or stress',
    descriptionUr: 'صحت مند پودا جس میں بیماری یا تناؤ کی کوئی علامت نہیں',
    symptomsEn: 'Normal green color, no lesions, no abnormal growth patterns',
    symptomsUr: 'عام سبز رنگ، کوئی زخم نہیں، کوئی غیر معمولی نشوونما نہیں',
  },
  
  // ============ WHEAT DISEASES (Class 1-9) ============
  {
    id: 'disease-001',
    classId: 1,
    nameEn: 'Wheat Leaf Rust',
    nameUr: 'گندم کا پتا زنگ',
    namePa: 'کڻک دی پتی زنگ',
    nameSd: 'ڪڻڪ جي پتي زنگ',
    scientificName: 'Puccinia triticina',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Fungal disease causing orange-brown pustules on wheat leaves',
    descriptionUr: 'فنگس کی بیماری جو گندم کے پتوں پر نارنجی بھورے دھبے بناتی ہے',
    symptomsEn: 'Orange-brown pustules on leaves, yellowing, premature leaf death',
    symptomsUr: 'پتوں پر نارنجی بھورے دھبے، پیلا پن، پتوں کی قبل از وقت موت',
  },
  {
    id: 'disease-002',
    classId: 2,
    nameEn: 'Wheat Yellow Rust',
    nameUr: 'گندم کا زرد زنگ',
    namePa: 'کڻک دا پیلا زنگ',
    nameSd: 'ڪڻڪ جو پيلو زنگ',
    scientificName: 'Puccinia striiformis',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Highly destructive fungal disease forming yellow stripes on wheat',
    descriptionUr: 'انتہائی تباہ کن فنگل بیماری جو گندم پر پیلی دھاریاں بناتی ہے',
    symptomsEn: 'Yellow-orange stripes on leaves, stunted growth, reduced yield',
    symptomsUr: 'پتوں پر زرد نارنجی دھاریاں، نشوونما میں رکاوٹ، پیداوار میں کمی',
  },
  {
    id: 'disease-003',
    classId: 3,
    nameEn: 'Wheat Stem Rust',
    nameUr: 'گندم کا تنے کا زنگ',
    namePa: 'کڻک دے تنے دا زنگ',
    nameSd: 'ڪڻڪ جي ٿلهي جو زنگ',
    scientificName: 'Puccinia graminis',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Black rust fungus attacking wheat stems and leaves',
    descriptionUr: 'کالا زنگ فنگس جو گندم کے تنوں اور پتوں پر حملہ کرتا ہے',
    symptomsEn: 'Black pustules on stems, leaf sheath, lodging',
    symptomsUr: 'تنوں پر کالے دھبے، پتوں کا غلاف، گرنا',
  },
  {
    id: 'disease-004',
    classId: 4,
    nameEn: 'Wheat Powdery Mildew',
    nameUr: 'گندم کی سفید پودری بیماری',
    namePa: 'کڻک دی چٹی پوڈری بیماری',
    nameSd: 'ڪڻڪ جي اڇي پاڻي جي بيماري',
    scientificName: 'Blumeria graminis',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['wheat'],
    descriptionEn: 'White powdery fungal growth on wheat leaves',
    descriptionUr: 'گندم کے پتوں پر سفید پودری فنگس کی نشوونما',
    symptomsEn: 'White powdery patches on leaves, yellowing',
    symptomsUr: 'پتوں پر سفید پودری دھبے، پیلا پن',
  },
  {
    id: 'disease-005',
    classId: 5,
    nameEn: 'Wheat Septoria Leaf Blotch',
    nameUr: 'گندم کے پتے کا دھبہ',
    namePa: 'کڻک دے پتے دا دھبا',
    nameSd: 'ڪڻڪ جي پتي جو داغ',
    scientificName: 'Septoria tritici',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Fungal disease causing lesions on wheat leaves',
    descriptionUr: 'فنگل بیماری جو گندم کے پتوں پر زخم بناتی ہے',
    symptomsEn: 'Brown lesions with yellow halo on leaves',
    symptomsUr: 'پتوں پر پیلے ہالے والے بھورے زخم',
  },
  {
    id: 'disease-006',
    classId: 6,
    nameEn: 'Wheat Fusarium Head Blight',
    nameUr: 'گندم کے سر کی سڑن',
    namePa: 'کڻک دے سر دی سڑن',
    nameSd: 'ڪڻڪ جي سر جي سڙڻ',
    scientificName: 'Fusarium graminearum',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Fungal disease affecting wheat heads, produces toxins',
    descriptionUr: 'فنگل بیماری جو گندم کے سروں کو متاثر کرتی ہے، زہریلے مادے پیدا کرتی ہے',
    symptomsEn: 'Bleached wheat heads, pink fungal growth',
    symptomsUr: 'سفید گندم کے سر، گلابی فنگل نشوونما',
  },
  {
    id: 'disease-007',
    classId: 7,
    nameEn: 'Wheat Aphids',
    nameUr: 'گندم کے شپشے',
    namePa: 'کڻک دے شپشے',
    nameSd: 'ڪڻڪ جي مکيون',
    scientificName: 'Sitobion avenae',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Small sap-sucking insects on wheat plants',
    descriptionUr: 'گندم کے پودوں پر چھوٹے رس چوسنے والے کیڑے',
    symptomsEn: 'Clusters of small insects on leaves, sticky honeydew',
    symptomsUr: 'پتوں پر چھوٹے کیڑوں کے جھنڈ، چپچپا شہد',
  },
  {
    id: 'disease-008',
    classId: 8,
    nameEn: 'Wheat Armyworm',
    nameUr: 'گندم کا فوجی کیڑا',
    namePa: 'کڻک دا فوجی کیڑا',
    nameSd: 'ڪڻڪ جو فوجي کيڙو',
    scientificName: 'Mythimna separata',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Caterpillars feeding on wheat leaves and heads',
    descriptionUr: 'کیڑے جو گندم کے پتوں اور سروں کو کھاتے ہیں',
    symptomsEn: 'Defoliation, chewed leaves, larvae visible',
    symptomsUr: 'پتوں کی کمی، چبائے ہوئے پتے، لاروا نظر آتے ہیں',
  },

  // ============ RICE DISEASES (Class 10-19) ============
  {
    id: 'disease-010',
    classId: 10,
    nameEn: 'Rice Blast',
    nameUr: 'چاول کا دھماکہ',
    namePa: 'چول دا دھماکا',
    nameSd: 'چانورن جو ڌماڪو',
    scientificName: 'Pyricularia oryzae',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['rice'],
    descriptionEn: 'Most devastating fungal disease of rice worldwide',
    descriptionUr: 'دنیا بھر میں چاول کی سب سے تباہ کن فنگل بیماری',
    symptomsEn: 'Diamond-shaped lesions on leaves, neck rot',
    symptomsUr: 'پتوں پر ہیرے کی شکل کے زخم، گردن کی سڑن',
  },
  {
    id: 'disease-011',
    classId: 11,
    nameEn: 'Rice Bacterial Leaf Blight',
    nameUr: 'چاول کے پتے کی بیکٹیریل بیماری',
    namePa: 'چول دے پتے دی بیکٹیریل بیماری',
    nameSd: 'چانورن جي پتي جي بيڪٽيريل بيماري',
    scientificName: 'Xanthomonas oryzae',
    category: DISEASE_CATEGORIES.BACTERIAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['rice'],
    descriptionEn: 'Bacterial disease causing leaf yellowing and wilting',
    descriptionUr: 'بیکٹیریل بیماری جو پتوں کو پیلا اور مرجھانے کا سبب بنتی ہے',
    symptomsEn: 'Water-soaked lesions, yellowing from leaf tips',
    symptomsUr: 'پانی سے بھرے زخم، پتوں کے سروں سے پیلا پن',
  },
  {
    id: 'disease-012',
    classId: 12,
    nameEn: 'Rice Sheath Blight',
    nameUr: 'چاول کے غلاف کی بیماری',
    namePa: 'چول دے غلاف دی بیماری',
    nameSd: 'چانورن جي غلاف جي بيماري',
    scientificName: 'Rhizoctonia solani',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['rice'],
    descriptionEn: 'Fungal disease attacking rice leaf sheaths',
    descriptionUr: 'فنگل بیماری جو چاول کے پتوں کے غلاف پر حملہ کرتی ہے',
    symptomsEn: 'Elliptical lesions on leaf sheaths, lodging',
    symptomsUr: 'پتوں کے غلاف پر بیضوی زخم، گرنا',
  },
  {
    id: 'disease-013',
    classId: 13,
    nameEn: 'Rice Brown Spot',
    nameUr: 'چاول کا بھورا دھبہ',
    namePa: 'چول دا بھورا دھبا',
    nameSd: 'چانورن جو ڀورو داغ',
    scientificName: 'Bipolaris oryzae',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['rice'],
    descriptionEn: 'Fungal disease causing brown spots on rice leaves',
    descriptionUr: 'فنگل بیماری جو چاول کے پتوں پر بھورے دھبے بناتی ہے',
    symptomsEn: 'Circular brown spots on leaves and grains',
    symptomsUr: 'پتوں اور دانوں پر گول بھورے دھبے',
  },
  {
    id: 'disease-014',
    classId: 14,
    nameEn: 'Rice Stem Borer',
    nameUr: 'چاول کا تنے کا کیڑا',
    namePa: 'چول دے تنے دا کیڑا',
    nameSd: 'چانورن جي ٿلهي جو کيڙو',
    scientificName: 'Scirpophaga incertulas',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['rice'],
    descriptionEn: 'Insect pest boring into rice stems',
    descriptionUr: 'کیڑا جو چاول کے تنوں میں سوراخ کرتا ہے',
    symptomsEn: 'Dead hearts in vegetative stage, white heads in reproductive stage',
    symptomsUr: 'نباتی مرحلے میں مردہ دل، تولیدی مرحلے میں سفید سر',
  },
  {
    id: 'disease-015',
    classId: 15,
    nameEn: 'Rice Hispa',
    nameUr: 'چاول کا ہسپا کیڑا',
    namePa: 'چول دا ہسپا کیڑا',
    nameSd: 'چانورن جو هسپا کيڙو',
    scientificName: 'Dicladispa armigera',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['rice'],
    descriptionEn: 'Beetle that mines rice leaves',
    descriptionUr: 'بیٹل جو چاول کے پتوں کو کھودتا ہے',
    symptomsEn: 'White streaks on leaves, leaf mining',
    symptomsUr: 'پتوں پر سفید دھاریاں، پتوں کی کھدائی',
  },
  {
    id: 'disease-016',
    classId: 16,
    nameEn: 'Rice Healthy',
    nameUr: 'چاول صحت مند',
    namePa: 'چول صحت مند',
    nameSd: 'چانور صحتمند',
    scientificName: null,
    category: DISEASE_CATEGORIES.OTHER,
    severity: null,
    affectedCrops: ['rice'],
    descriptionEn: 'Healthy rice plant with no visible disease or pest damage',
    descriptionUr: 'صحت مند چاول کا پودا بغیر کسی بیماری یا کیڑوں کے نقصان کے',
    symptomsEn: 'Green healthy leaves, normal growth',
    symptomsUr: 'سبز صحت مند پتے، معمول کی نشوونما',
  },

  // ============ COTTON DISEASES (Class 20-29) ============
  {
    id: 'disease-020',
    classId: 20,
    nameEn: 'Cotton Leaf Curl Virus',
    nameUr: 'کپاس کے پتے کی لپٹی بیماری',
    namePa: 'کپاہ دے پتے دی لپٹی بیماری',
    nameSd: 'ڪپاس جي پتي جي لپيٽ واري بيماري',
    scientificName: 'Cotton leaf curl virus',
    category: DISEASE_CATEGORIES.VIRAL,
    severity: SEVERITY_LEVELS.CRITICAL,
    affectedCrops: ['cotton'],
    descriptionEn: 'Most devastating viral disease of cotton in Pakistan',
    descriptionUr: 'پاکستان میں کپاس کی سب سے تباہ کن وائرل بیماری',
    symptomsEn: 'Leaf curling, vein thickening, stunted growth',
    symptomsUr: 'پتوں کا لپٹنا، رگوں کا موٹا ہونا، نشوونما میں رکاوٹ',
  },
  {
    id: 'disease-021',
    classId: 21,
    nameEn: 'Cotton Bollworm',
    nameUr: 'کپاس کا گولے کا کیڑا',
    namePa: 'کپاہ دا گولے دا کیڑا',
    nameSd: 'ڪپاس جو گولي جو کيڙو',
    scientificName: 'Helicoverpa armigera',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['cotton'],
    descriptionEn: 'Major cotton pest attacking bolls',
    descriptionUr: 'بڑا کپاس کا کیڑا جو گولوں پر حملہ کرتا ہے',
    symptomsEn: 'Holes in bolls, damaged seeds, larvae visible',
    symptomsUr: 'گولوں میں سوراخ، خراب بیج، لاروا نظر آتے ہیں',
  },
  {
    id: 'disease-022',
    classId: 22,
    nameEn: 'Cotton Whitefly',
    nameUr: 'کپاس کی سفید مکھی',
    namePa: 'کپاہ دی چٹی مکھی',
    nameSd: 'ڪپاس جي اڇي مکيءَ',
    scientificName: 'Bemisia tabaci',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['cotton'],
    descriptionEn: 'Vector of cotton leaf curl virus, direct pest',
    descriptionUr: 'کپاس کے پتے کی لپٹی وائرس کا ناقل، براہ راست کیڑا',
    symptomsEn: 'Whitefly clusters on leaf undersides, leaf yellowing, honeydew',
    symptomsUr: 'پتوں کے نیچے سفید مکھیوں کے جھنڈ، پتوں کا پیلا پن، شہد',
  },
  {
    id: 'disease-023',
    classId: 23,
    nameEn: 'Cotton Jassids',
    nameUr: 'کپاس کے جاسڈ کیڑے',
    namePa: 'کپاہ دے جاسڈ کیڑے',
    nameSd: 'ڪپاس جا جاسڊ کيڙا',
    scientificName: 'Amrasca biguttula',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['cotton'],
    descriptionEn: 'Leaf hoppers sucking sap from cotton plants',
    descriptionUr: 'پتوں کے کیڑے جو کپاس کے پودوں سے رس چوستے ہیں',
    symptomsEn: 'Leaf edge yellowing (hopper burn), curling',
    symptomsUr: 'پتوں کے کناروں کا پیلا پن (ہاپر جلن), لپٹنا',
  },
  {
    id: 'disease-024',
    classId: 24,
    nameEn: 'Cotton Bacterial Blight',
    nameUr: 'کپاس کی بیکٹیریل بیماری',
    namePa: 'کپاہ دی بیکٹیریل بیماری',
    nameSd: 'ڪپاس جي بيڪٽيريل بيماري',
    scientificName: 'Xanthomonas axonopodis',
    category: DISEASE_CATEGORIES.BACTERIAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['cotton'],
    descriptionEn: 'Bacterial disease causing angular leaf spots',
    descriptionUr: 'بیکٹیریل بیماری جو پتوں پر کونیا دھبے بناتی ہے',
    symptomsEn: 'Angular water-soaked lesions on leaves',
    symptomsUr: 'پتوں پر کونیا پانی سے بھرے زخم',
  },
  {
    id: 'disease-025',
    classId: 25,
    nameEn: 'Cotton Fusarium Wilt',
    nameUr: 'کپاس کی مرجھانے کی بیماری',
    namePa: 'کپاہ دی مرجھانے دی بیماری',
    nameSd: 'ڪپاس جي مرجهائڻ جي بيماري',
    scientificName: 'Fusarium oxysporum',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['cotton'],
    descriptionEn: 'Soil-borne fungal disease causing vascular wilt',
    descriptionUr: 'مٹی سے پھیلنے والی فنگل بیماری جو عروقی مرجھانے کا سبب بنتی ہے',
    symptomsEn: 'Yellowing, wilting, vascular browning',
    symptomsUr: 'پیلا پن، مرجھانا، عروقی بھورا پن',
  },
  {
    id: 'disease-026',
    classId: 26,
    nameEn: 'Cotton Healthy',
    nameUr: 'کپاس صحت مند',
    namePa: 'کپاہ صحت مند',
    nameSd: 'ڪپاس صحتمند',
    scientificName: null,
    category: DISEASE_CATEGORIES.OTHER,
    severity: null,
    affectedCrops: ['cotton'],
    descriptionEn: 'Healthy cotton plant with no visible disease or pest damage',
    descriptionUr: 'صحت مند کپاس کا پودا بغیر کسی بیماری یا کیڑوں کے نقصان کے',
    symptomsEn: 'Green healthy leaves, normal growth',
    symptomsUr: 'سبز صحت مند پتے، معمول کی نشوونما',
  },

  // ============ SUGARCANE DISEASES (Class 30-36) ============
  {
    id: 'disease-030',
    classId: 30,
    nameEn: 'Sugarcane Red Rot',
    nameUr: 'گنے کی سرخ سڑن',
    namePa: 'گنے دی لال سڑن',
    nameSd: 'گني جي ڳاڙهي سڙڻ',
    scientificName: 'Colletotrichum falcatum',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Most serious disease of sugarcane',
    descriptionUr: 'گنے کی سب سے سنگین بیماری',
    symptomsEn: 'Red discoloration inside stem, white patches',
    symptomsUr: 'تنے کے اندر سرخ رنگ، سفید دھبے',
  },
  {
    id: 'disease-031',
    classId: 31,
    nameEn: 'Sugarcane Smut',
    nameUr: 'گنے کا کالا مرض',
    namePa: 'گنے دا کالا مرض',
    nameSd: 'گني جو ڪارو مرض',
    scientificName: 'Sporisorium scitamineum',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Fungal disease producing black whip-like structure',
    descriptionUr: 'فنگل بیماری جو کالی کوڑے جیسی ساخت بناتی ہے',
    symptomsEn: 'Black whip emerging from growing point',
    symptomsUr: 'بڑھتے ہوئے نقطے سے کالی کوڑا نکلنا',
  },
  {
    id: 'disease-032',
    classId: 32,
    nameEn: 'Sugarcane Rust',
    nameUr: 'گنے کا زنگ',
    namePa: 'گنے دا زنگ',
    nameSd: 'گني جو زنگ',
    scientificName: 'Puccinia melanocephala',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Rust fungus on sugarcane leaves',
    descriptionUr: 'گنے کے پتوں پر زنگ فنگس',
    symptomsEn: 'Orange-brown pustules on leaves',
    symptomsUr: 'پتوں پر نارنجی بھورے دھبے',
  },
  {
    id: 'disease-033',
    classId: 33,
    nameEn: 'Sugarcane Borer Complex',
    nameUr: 'گنے کے سوراخ کرنے والے کیڑے',
    namePa: 'گنے دے سوراخ کرن والے کیڑے',
    nameSd: 'گني جا سوراخ ڪرڻ وارا کيڙا',
    scientificName: 'Multiple species',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Various insect borers attacking sugarcane stems',
    descriptionUr: 'مختلف کیڑے جو گنے کے تنوں پر حملہ کرتے ہیں',
    symptomsEn: 'Stem tunneling, dead hearts, reduced sugar content',
    symptomsUr: 'تنے میں سرنگیں، مردہ دل، شکر کی مقدار میں کمی',
  },
  {
    id: 'disease-034',
    classId: 34,
    nameEn: 'Sugarcane Healthy',
    nameUr: 'گنا صحت مند',
    namePa: 'گنا صحت مند',
    nameSd: 'گني صحتمند',
    scientificName: null,
    category: DISEASE_CATEGORIES.OTHER,
    severity: null,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Healthy sugarcane plant with no visible disease or pest damage',
    descriptionUr: 'صحت مند گنے کا پودا بغیر کسی بیماری یا کیڑوں کے نقصان کے',
    symptomsEn: 'Green healthy stalks, normal growth',
    symptomsUr: 'سبز صحت مند ڈنٹھل، معمول کی نشوونما',
  },

  // ============ CORN/MAIZE DISEASES (Class 40-46) ============
  {
    id: 'disease-040',
    classId: 40,
    nameEn: 'Corn Northern Leaf Blight',
    nameUr: 'مکئی کے پتے کی شمالی بیماری',
    namePa: 'مکئی دے پتے دی اتری بیماری',
    nameSd: 'مکئي جي پتي جي اترئين بيماري',
    scientificName: 'Setosphaeria turcica',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['corn'],
    descriptionEn: 'Fungal disease causing long lesions on corn leaves',
    descriptionUr: 'فنگل بیماری جو مکئی کے پتوں پر لمبے زخم بناتی ہے',
    symptomsEn: 'Long grayish-green lesions on leaves',
    symptomsUr: 'پتوں پر لمبے سرمئی سبز زخم',
  },
  {
    id: 'disease-041',
    classId: 41,
    nameEn: 'Corn Common Rust',
    nameUr: 'مکئی کا عام زنگ',
    namePa: 'مکئی دا عام زنگ',
    nameSd: 'مکئي جو عام زنگ',
    scientificName: 'Puccinia sorghi',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['corn'],
    descriptionEn: 'Common rust disease of corn',
    descriptionUr: 'مکئی کی عام زنگ بیماری',
    symptomsEn: 'Reddish-brown pustules on leaves',
    symptomsUr: 'پتوں پر سرخی مائل بھورے دھبے',
  },
  {
    id: 'disease-042',
    classId: 42,
    nameEn: 'Corn Gray Leaf Spot',
    nameUr: 'مکئی کے پتے کا سرمئی دھبہ',
    namePa: 'مکئی دے پتے دا سرمئی دھبا',
    nameSd: 'مکئي جي پتي جو سرمائي داغ',
    scientificName: 'Cercospora zeae-maydis',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['corn'],
    descriptionEn: 'Fungal disease causing rectangular gray lesions',
    descriptionUr: 'فنگل بیماری جو مستطیل سرمئی زخم بناتی ہے',
    symptomsEn: 'Rectangular gray lesions on leaves',
    symptomsUr: 'پتوں پر مستطیل سرمئی زخم',
  },
  {
    id: 'disease-043',
    classId: 43,
    nameEn: 'Corn Borer',
    nameUr: 'مکئی کا سوراخ کرنے والا کیڑا',
    namePa: 'مکئی دا سوراخ کرن والا کیڑا',
    nameSd: 'مکئي جو سوراخ ڪرڻ وارو کيڙو',
    scientificName: 'Ostrinia nubilalis',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['corn'],
    descriptionEn: 'Insect pest boring into corn stems',
    descriptionUr: 'کیڑا جو مکئی کے تنوں میں سوراخ کرتا ہے',
    symptomsEn: 'Holes in stalks, broken tassels, lodging',
    symptomsUr: 'ڈنٹھلوں میں سوراخ، ٹوٹے ہوئے پھول، گرنا',
  },
  {
    id: 'disease-044',
    classId: 44,
    nameEn: 'Corn Healthy',
    nameUr: 'مکئی صحت مند',
    namePa: 'مکئی صحت مند',
    nameSd: 'مکئي صحتمند',
    scientificName: null,
    category: DISEASE_CATEGORIES.OTHER,
    severity: null,
    affectedCrops: ['corn'],
    descriptionEn: 'Healthy corn plant with no visible disease or pest damage',
    descriptionUr: 'صحت مند مکئی کا پودا بغیر کسی بیماری یا کیڑوں کے نقصان کے',
    symptomsEn: 'Green healthy leaves, normal growth',
    symptomsUr: 'سبز صحت مند پتے، معمول کی نشوونما',
  },

  // ============ NUTRIENT DEFICIENCIES (Class 50-55) ============
  {
    id: 'disease-050',
    classId: 50,
    nameEn: 'Nitrogen Deficiency',
    nameUr: 'نائٹروجن کی کمی',
    namePa: 'نائٹروجن دی کمی',
    nameSd: 'نائٽروجن جي گھٽ',
    scientificName: null,
    category: DISEASE_CATEGORIES.NUTRIENT_DEFICIENCY,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['wheat', 'rice', 'corn', 'cotton', 'sugarcane'],
    descriptionEn: 'Lack of nitrogen causing yellowing of older leaves',
    descriptionUr: 'نائٹروجن کی کمی جو پرانے پتوں کے پیلے پن کا سبب بنتی ہے',
    symptomsEn: 'Yellowing of older leaves, stunted growth',
    symptomsUr: 'پرانے پتوں کا پیلا پن، نشوونما میں رکاوٹ',
  },
  {
    id: 'disease-051',
    classId: 51,
    nameEn: 'Phosphorus Deficiency',
    nameUr: 'فاسفورس کی کمی',
    namePa: 'فاسفورس دی کمی',
    nameSd: 'فاسفورس جي گھٽ',
    scientificName: null,
    category: DISEASE_CATEGORIES.NUTRIENT_DEFICIENCY,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['wheat', 'rice', 'corn', 'cotton', 'sugarcane'],
    descriptionEn: 'Phosphorus deficiency causing purple discoloration',
    descriptionUr: 'فاسفورس کی کمی جو جامنی رنگ کا سبب بنتی ہے',
    symptomsEn: 'Purple discoloration, reduced tillering',
    symptomsUr: 'جامنی رنگ، کلوں میں کمی',
  },
  {
    id: 'disease-052',
    classId: 52,
    nameEn: 'Potassium Deficiency',
    nameUr: 'پوٹاشیم کی کمی',
    namePa: 'پوٹاشیم دی کمی',
    nameSd: 'پوٽاشيم جي گھٽ',
    scientificName: null,
    category: DISEASE_CATEGORIES.NUTRIENT_DEFICIENCY,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['wheat', 'rice', 'corn', 'cotton', 'sugarcane'],
    descriptionEn: 'Potassium deficiency causing leaf edge burning',
    descriptionUr: 'پوٹاشیم کی کمی جو پتوں کے کناروں کی جلن کا سبب بنتی ہے',
    symptomsEn: 'Browning and scorching of leaf edges',
    symptomsUr: 'پتوں کے کناروں کا بھورا پن اور جلنا',
  },
  {
    id: 'disease-053',
    classId: 53,
    nameEn: 'Iron Deficiency',
    nameUr: 'آئرن کی کمی',
    namePa: 'لوہے دی کمی',
    nameSd: 'لوهه جي گھٽ',
    scientificName: null,
    category: DISEASE_CATEGORIES.NUTRIENT_DEFICIENCY,
    severity: SEVERITY_LEVELS.MILD,
    affectedCrops: ['wheat', 'rice', 'corn', 'cotton', 'sugarcane'],
    descriptionEn: 'Iron deficiency causing interveinal chlorosis',
    descriptionUr: 'آئرن کی کمی جو رگوں کے درمیان پیلا پن کا سبب بنتی ہے',
    symptomsEn: 'Yellowing between leaf veins, young leaves affected',
    symptomsUr: 'پتوں کی رگوں کے درمیان پیلا پن، نوجوان پتے متاثر',
  },
  {
    id: 'disease-054',
    classId: 54,
    nameEn: 'Zinc Deficiency',
    nameUr: 'زنک کی کمی',
    namePa: 'زنک دی کمی',
    nameSd: 'زنڪ جي گھٽ',
    scientificName: null,
    category: DISEASE_CATEGORIES.NUTRIENT_DEFICIENCY,
    severity: SEVERITY_LEVELS.MILD,
    affectedCrops: ['wheat', 'rice', 'corn', 'cotton', 'sugarcane'],
    descriptionEn: 'Zinc deficiency causing stunted growth and chlorosis',
    descriptionUr: 'زنک کی کمی جو نشوونما میں رکاوٹ اور پیلا پن کا سبب بنتی ہے',
    symptomsEn: 'Stunted growth, chlorotic stripes, short internodes',
    symptomsUr: 'نشوونما میں رکاوٹ، پیلی دھاریاں، چھوٹے انٹرنوڈز',
  },
  
  // ============ ADDITIONAL DISEASE CLASSES (9, 17-19, 27-29, 35-39, 45-49) ============
  {
    id: 'disease-009',
    classId: 9,
    nameEn: 'Wheat Head Blight',
    nameUr: 'گندم کا سر جھلساؤ',
    namePa: 'کڻک دا سر جھلساؤ',
    nameSd: 'ڪڻڪ جو مٿو سڙ',
    scientificName: 'Fusarium graminearum',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['wheat'],
    descriptionEn: 'Fungal disease causing head blight and toxin contamination in wheat',
    descriptionUr: 'فنگس کی بیماری جو گندم کے سر میں جھلساؤ اور زہریلے مواد کا سبب بنتی ہے',
    symptomsEn: 'Bleached spikelets, pink-orange spore masses, shriveled kernels',
    symptomsUr: 'بلیچ شدہ بالیں، گلابی نارنجی بیجاणو کے ڈھیر، سکڑے ہوئے دانے',
  },
  {
    id: 'disease-017',
    classId: 17,
    nameEn: 'Rice False Smut',
    nameUr: 'چاول کا جھوٹا سموٹ',
    namePa: 'چاول دا جھوٹا سموٹ',
    nameSd: 'چانور جو ڪوڙو سموٽ',
    scientificName: 'Ustilaginoidea virens',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['rice'],
    descriptionEn: 'Fungal disease affecting rice grains with orange-yellow spore balls',
    descriptionUr: 'فنگس کی بیماری جو چاول کے دانوں پر نارنجی پیلے بیجاणو کی گیندیں بناتی ہے',
    symptomsEn: 'Orange-yellow spore balls on grains, reduced grain quality',
    symptomsUr: 'دانوں پر نارنجی پیلی بیجاणو کی گیندیں، دانے کے معیار میں کمی',
  },
  {
    id: 'disease-018',
    classId: 18,
    nameEn: 'Rice Sheath Rot',
    nameUr: 'چاول کی غلاف سڑن',
    namePa: 'چاول دی چھلکی سڑ',
    nameSd: 'چانور جي ڍڪ سڙ',
    scientificName: 'Sarocladium oryzae',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['rice'],
    descriptionEn: 'Fungal disease causing sheath rot and grain discoloration',
    descriptionUr: 'فنگس کی بیماری جو غلاف کی سڑن اور دانے کی رنگت میں تبدیلی کا سبب بنتی ہے',
    symptomsEn: 'Sheath rot, grain discoloration, reduced grain filling',
    symptomsUr: 'غلاف کی سڑن، دانے کی رنگت میں تبدیلی، دانے بھرنے میں کمی',
  },
  {
    id: 'disease-019',
    classId: 19,
    nameEn: 'Rice Grain Discoloration',
    nameUr: 'چاول کے دانے کی رنگت میں تبدیلی',
    namePa: 'چاول دے داݨے دی رنگت وچ تبدیلی',
    nameSd: 'چانور جي داڻي جي رنگ ۾ تبديلي',
    scientificName: 'Various pathogens',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MILD,
    affectedCrops: ['rice'],
    descriptionEn: 'Complex of fungal pathogens causing grain discoloration',
    descriptionUr: 'فنگس کے مختلف جراثیم جو دانے کی رنگت میں تبدیلی کا سبب بنتے ہیں',
    symptomsEn: 'Brown, black, or pinkish discoloration of grains',
    symptomsUr: 'دانوں پر بھورا، کالا، یا گلابی رنگ',
  },
  {
    id: 'disease-027',
    classId: 27,
    nameEn: 'Cotton Fusarium Wilt',
    nameUr: 'کپاس کا فیوزیریم مرجھانا',
    namePa: 'کپاہ دا فیوزیریم مرجھانا',
    nameSd: 'ڪپهه جو فيوزيريم مرجھاڻ',
    scientificName: 'Fusarium oxysporum f.sp. vasinfectum',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['cotton'],
    descriptionEn: 'Soilborne fungal disease causing vascular wilt in cotton',
    descriptionUr: 'مٹی سے پھیلنے والی فنگس کی بیماری جو کپاس میں عروقی مرجھانے کا سبب بنتی ہے',
    symptomsEn: 'Yellowing, wilting, vascular discoloration, plant death',
    symptomsUr: 'پیلا پن، مرجھانا، عروق کی رنگت میں تبدیلی، پودے کی موت',
  },
  {
    id: 'disease-028',
    classId: 28,
    nameEn: 'Cotton Verticillium Wilt',
    nameUr: 'کپاس کا ورٹیسیلیم مرجھانا',
    namePa: 'کپاہ دا ورٹیسیلیم مرجھانا',
    nameSd: 'ڪپهه جو ورٽيسيليم مرجھاڻ',
    scientificName: 'Verticillium dahliae',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['cotton'],
    descriptionEn: 'Fungal disease causing wilt and leaf discoloration in cotton',
    descriptionUr: 'فنگس کی بیماری جو کپاس میں مرجھانے اور پتوں کی رنگت میں تبدیلی کا سبب بنتی ہے',
    symptomsEn: 'Yellowing between leaf veins, wilting, defoliation',
    symptomsUr: 'پتوں کی رگوں کے درمیان پیلا پن، مرجھانا، پتے گرنا',
  },
  {
    id: 'disease-029',
    classId: 29,
    nameEn: 'Cotton Aphids',
    nameUr: 'کپاس کے شپشے',
    namePa: 'کپاہ دے جُوآں',
    nameSd: 'ڪپهه جا جوئون',
    scientificName: 'Aphis gossypii',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['cotton', 'sugarcane'],
    descriptionEn: 'Sucking insect pest causing leaf curling and honeydew secretion',
    descriptionUr: 'چوسنے والا کیڑا جو پتوں کے مڑنے اور شہد کی بوندوں کا سبب بنتا ہے',
    symptomsEn: 'Leaf curling, stunted growth, honeydew, sooty mold',
    symptomsUr: 'پتے مڑنا، نشوونما رکنا، شہد کی بوندیں، کالی پھپھوند',
  },
  {
    id: 'disease-035',
    classId: 35,
    nameEn: 'Sugarcane Pineapple Disease',
    nameUr: 'گنے کی انناس بیماری',
    namePa: 'گنے دی اناناس بیماری',
    nameSd: 'ڪمند جي انناس بيماري',
    scientificName: 'Ceratocystis paradoxa',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Fungal disease affecting sugarcane sets and causing pineapple odor',
    descriptionUr: 'فنگس کی بیماری جو گنے کے ٹکڑوں کو متاثر کرتی ہے اور انناس کی بو دیتی ہے',
    symptomsEn: 'Reddening of sets, pineapple odor, rotting, poor germination',
    symptomsUr: 'ٹکڑوں کا سرخ ہونا، انناس کی بو، سڑن، کم اگنا',
  },
  {
    id: 'disease-036',
    classId: 36,
    nameEn: 'Sugarcane Whip Smut',
    nameUr: 'گنے کا چابک سموٹ',
    namePa: 'گنے دا کوڑا سموٹ',
    nameSd: 'ڪمند جو ڪوڙو سموٽ',
    scientificName: 'Sporisorium scitamineum',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Fungal disease causing whip-like growth with black spores',
    descriptionUr: 'فنگس کی بیماری جو چابک جیسی نشوونما اور کالے بیجاणو کا سبب بنتی ہے',
    symptomsEn: 'Whip-like structure with black spores, reduced tillering',
    symptomsUr: 'چابک جیسی ساخت کالے بیجاণوں کے ساتھ، کلوں کی کمی',
  },
  {
    id: 'disease-037',
    classId: 37,
    nameEn: 'Sugarcane Mosaic Virus',
    nameUr: 'گنے کا موزیک وائرس',
    namePa: 'گنے دا موزیک وائرس',
    nameSd: 'ڪمند جو موزيڪ وائرس',
    scientificName: 'Sugarcane mosaic virus (SCMV)',
    category: DISEASE_CATEGORIES.VIRAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['sugarcane', 'corn'],
    descriptionEn: 'Viral disease causing mosaic patterns on sugarcane leaves',
    descriptionUr: 'وائرل بیماری جو گنے کے پتوں پر موزیک نمونے بناتی ہے',
    symptomsEn: 'Mosaic patterns, chlorotic streaks, stunted growth',
    symptomsUr: 'موزیک نمونے، پیلی دھاریاں، نشوونما میں رکاوٹ',
  },
  {
    id: 'disease-038',
    classId: 38,
    nameEn: 'Sugarcane Scale Insects',
    nameUr: 'گنے کے شیلڈ کیڑے',
    namePa: 'گنے دے ڈھال کیڑے',
    nameSd: 'ڪمند جا ڍال ڪيڙا',
    scientificName: 'Melanaspis glomerata',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Scale insect pest causing yellowing and reduced vigor',
    descriptionUr: 'شیلڈ کیڑا جو پیلا پن اور طاقت میں کمی کا سبب بنتا ہے',
    symptomsEn: 'Scale insects on stems, yellowing, reduced growth',
    symptomsUr: 'تنوں پر کیڑے، پیلا پن، نشوونما میں کمی',
  },
  {
    id: 'disease-039',
    classId: 39,
    nameEn: 'Sugarcane Yellow Leaf Virus',
    nameUr: 'گنے کا پیلا پتا وائرس',
    namePa: 'گنے دا پیلا پتا وائرس',
    nameSd: 'ڪمند جو پيلو پتو وائرس',
    scientificName: 'Sugarcane yellow leaf virus (ScYLV)',
    category: DISEASE_CATEGORIES.VIRAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['sugarcane'],
    descriptionEn: 'Viral disease causing yellowing of midrib on lower leaves',
    descriptionUr: 'وائرل بیماری جو نچلے پتوں کی درمیانی رگ کے پیلا پن کا سبب بنتی ہے',
    symptomsEn: 'Yellowing of midrib on lower leaves, reduced sugar content',
    symptomsUr: 'نچلے پتوں کی درمیانی رگ کا پیلا پن، چینی کی مقدار میں کمی',
  },
  {
    id: 'disease-045',
    classId: 45,
    nameEn: 'Corn Common Rust',
    nameUr: 'مکئی کا عام زنگ',
    namePa: 'مکئی دا عام زنگ',
    nameSd: 'مڪئي جو عام زنگ',
    scientificName: 'Puccinia sorghi',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['corn'],
    descriptionEn: 'Fungal disease causing rust pustules on corn leaves',
    descriptionUr: 'فنگس کی بیماری جو مکئی کے پتوں پر زنگ کے دھبے بناتی ہے',
    symptomsEn: 'Circular to elongate brown pustules on leaves',
    symptomsUr: 'پتوں پر گول سے لمبے بھورے دھبے',
  },
  {
    id: 'disease-046',
    classId: 46,
    nameEn: 'Corn Fall Armyworm',
    nameUr: 'مکئی کا فال آرمی ورم',
    namePa: 'مکئی دا فال آرمی کیڑا',
    nameSd: 'مڪئي جو فال آرمي ڪيڙو',
    scientificName: 'Spodoptera frugiperda',
    category: DISEASE_CATEGORIES.PEST,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['corn', 'rice', 'sugarcane'],
    descriptionEn: 'Devastating caterpillar pest causing extensive foliar damage',
    descriptionUr: 'تباہ کن کیٹرپلر کیڑا جو پتوں کو بہت نقصان پہنچاتا ہے',
    symptomsEn: 'Large irregular holes in leaves, frass, severe defoliation',
    symptomsUr: 'پتوں میں بڑے بے ترتیب سوراخ، کیڑے کا فضلہ، پتے بہت گرنا',
  },
  {
    id: 'disease-047',
    classId: 47,
    nameEn: 'Corn Stalk Rot',
    nameUr: 'مکئی کے تنے کی سڑن',
    namePa: 'مکئی دے تنے دی سڑ',
    nameSd: 'مڪئي جي تني جي سڙ',
    scientificName: 'Fusarium spp.',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.SEVERE,
    affectedCrops: ['corn'],
    descriptionEn: 'Fungal disease causing stalk rot and lodging',
    descriptionUr: 'فنگس کی بیماری جو تنے کی سڑن اور گرنے کا سبب بنتی ہے',
    symptomsEn: 'Stalk rot, lodging, premature death, poor grain fill',
    symptomsUr: 'تنے کی سڑن، گرنا، جلد موت، دانے کم بھرنا',
  },
  {
    id: 'disease-048',
    classId: 48,
    nameEn: 'Corn Smut',
    nameUr: 'مکئی کا سموٹ',
    namePa: 'مکئی دا سموٹ',
    nameSd: 'مڪئي جو سموٽ',
    scientificName: 'Ustilago maydis',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['corn'],
    descriptionEn: 'Fungal disease causing large galls on ears and stalks',
    descriptionUr: 'فنگس کی بیماری جو بھٹوں اور تنوں پر بڑی گانٹھیں بناتی ہے',
    symptomsEn: 'Large galls filled with black spores on ears, tassels, stalks',
    symptomsUr: 'بھٹوں، پھولوں اور تنوں پر کالے بیجاणوں سے بھری بڑی گانٹھیں',
  },
  {
    id: 'disease-049',
    classId: 49,
    nameEn: 'Corn Downy Mildew',
    nameUr: 'مکئی کی سفید پھپھوند',
    namePa: 'مکئی دی چٹی پھپھوند',
    nameSd: 'مڪئي جي اڇي پفپونڊ',
    scientificName: 'Peronosclerospora spp.',
    category: DISEASE_CATEGORIES.FUNGAL,
    severity: SEVERITY_LEVELS.MODERATE,
    affectedCrops: ['corn'],
    descriptionEn: 'Fungal disease causing chlorotic streaks and stunting',
    descriptionUr: 'فنگس کی بیماری جو پیلی دھاریاں اور نشوونما میں رکاوٹ کا سبب بنتی ہے',
    symptomsEn: 'Chlorotic streaks, white growth on leaves, stunted plants',
    symptomsUr: 'پیلی دھاریاں، پتوں پر سفید نشوونما، پودے رک جانا',
  },
];

/**
 * Get disease by class ID
 * @param {number} classId - Model output class ID (0-54)
 * @returns {Object|null} Disease object or null if not found
 */
export function getDiseaseByClassId(classId) {
  return DISEASE_CLASSES.find((disease) => disease.classId === classId) || null;
}

/**
 * Get disease by ID
 * @param {string} diseaseId - Disease UUID
 * @returns {Object|null} Disease object or null if not found
 */
export function getDiseaseById(diseaseId) {
  return DISEASE_CLASSES.find((disease) => disease.id === diseaseId) || null;
}

/**
 * Get all diseases for a specific crop
 * @param {string} cropType - Crop type ('wheat', 'rice', 'cotton', etc.)
 * @returns {Array} Array of diseases affecting that crop
 */
export function getDiseasesByCrop(cropType) {
  return DISEASE_CLASSES.filter((disease) =>
    disease.affectedCrops.includes(cropType)
  );
}

/**
 * Get diseases by category
 * @param {string} category - Disease category
 * @returns {Array} Array of diseases in that category
 */
export function getDiseasesByCategory(category) {
  return DISEASE_CLASSES.filter((disease) => disease.category === category);
}

/**
 * Get disease name in specified language
 * @param {number} classId - Class ID
 * @param {string} lang - Language code ('en', 'ur', 'pa', 'sd')
 * @returns {string} Localized disease name
 */
export function getDiseaseName(classId, lang = 'ur') {
  const disease = getDiseaseByClassId(classId);
  if (!disease) return 'Unknown Disease';

  switch (lang) {
    case 'en':
      return disease.nameEn;
    case 'ur':
      return disease.nameUr;
    case 'pa':
      return disease.namePa;
    case 'sd':
      return disease.nameSd;
    default:
      return disease.nameUr; // Default to Urdu
  }
}

/**
 * Get total number of disease classes
 * @returns {number} Total classes
 */
export function getTotalClasses() {
  return DISEASE_CLASSES.length;
}

/**
 * Validate that all class IDs are unique and sequential
 * @returns {boolean} True if valid
 */
export function validateClassIds() {
  const classIds = DISEASE_CLASSES.map((d) => d.classId);
  const uniqueIds = new Set(classIds);
  
  if (classIds.length !== uniqueIds.size) {
    console.error('[DiseaseClasses] Duplicate class IDs found');
    return false;
  }
  
  return true;
}

export default {
  DISEASE_CATEGORIES,
  SEVERITY_LEVELS,
  DISEASE_CLASSES,
  getDiseaseByClassId,
  getDiseaseById,
  getDiseasesByCrop,
  getDiseasesByCategory,
  getDiseaseName,
  getTotalClasses,
  validateClassIds,
};

